package com.andy.music;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMDEVICE".
 */
public class COMDevice {

    private Long id;
    private String deviceName;
    private Integer deviceType;

    public COMDevice() {
    }

    public COMDevice(Long id) {
        this.id = id;
    }

    public COMDevice(Long id, String deviceName, Integer deviceType) {
        this.id = id;
        this.deviceName = deviceName;
        this.deviceType = deviceType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceName() {
        return deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    public Integer getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

}
