package com.andy.music;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MUSIC_1".
 */
public class Music_1 {

    private Long id;
    private String name;
    private String singer;
    private String time;
    private Boolean is_love;
    private String url;
    private String imgUrl;
    private Boolean local;
    private String path;

    public Music_1() {
    }

    public Music_1(Long id) {
        this.id = id;
    }

    public Music_1(Long id, String name, String singer, String time, Boolean is_love, String url, String imgUrl, Boolean local, String path) {
        this.id = id;
        this.name = name;
        this.singer = singer;
        this.time = time;
        this.is_love = is_love;
        this.url = url;
        this.imgUrl = imgUrl;
        this.local = local;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSinger() {
        return singer;
    }

    public void setSinger(String singer) {
        this.singer = singer;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Boolean getIs_love() {
        return is_love;
    }

    public void setIs_love(Boolean is_love) {
        this.is_love = is_love;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public Boolean getLocal() {
        return local;
    }

    public void setLocal(Boolean local) {
        this.local = local;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
