package com.andy.music;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROGRAM_1".
 */
public class Program_1 {

    private Long id;
    private String title;
    private String url;
    private String img_url;
    private String time;
    private Boolean is_love;

    public Program_1() {
    }

    public Program_1(Long id) {
        this.id = id;
    }

    public Program_1(Long id, String title, String url, String img_url, String time, Boolean is_love) {
        this.id = id;
        this.title = title;
        this.url = url;
        this.img_url = img_url;
        this.time = time;
        this.is_love = is_love;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImg_url() {
        return img_url;
    }

    public void setImg_url(String img_url) {
        this.img_url = img_url;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Boolean getIs_love() {
        return is_love;
    }

    public void setIs_love(Boolean is_love) {
        this.is_love = is_love;
    }

}
