/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_dsn_andy_bgmlauncher_auxin_MyJNI.h>
/* Header for class com_dsn_andy_bgmlauncher_auxin_MyJNI */

#ifndef _Included_com_dsn_andy_bgmlauncher_auxin_MyJNI
#define _Included_com_dsn_andy_bgmlauncher_auxin_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dsn_andy_bgmlauncher_auxin_MyJNI
 * Method:    setAuxin
 * Signature: (C)I
 */

JNIEXPORT jint JNICALL Java_com_dsn_andy_bgmlauncher_auxin_MyJNI_setAuxin
        (JNIEnv *, jclass, jchar);

/*
 * Class:     com_dsn_andy_bgmlauncher_auxin_MyJNI
 * Method:    getAuxin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dsn_andy_bgmlauncher_auxin_MyJNI_getAuxin
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
