//
// Created by dell on 2018/1/12.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include <stdio.h>
#include <fcntl.h>


/* Header for class com_dsn_andy_bgmlauncher_auxin_MyJNI */

#ifndef _Included_com_dsn_andy_bgmlauncher_auxin_MyJNI
#define _Included_com_dsn_andy_bgmlauncher_auxin_MyJNI
#ifdef __cplusplus
extern "C" {
#endif

int set_auxin(char mode)
{
    int fd;

    fd = open("/dev/misc_auxin",O_RDWR);
    if(fd<0){
        printf("****open serial port failed***\n");
        return -1;
    }

    if(mode != 'i' && mode != 'o'){
        printf("error mode\n");
        close(fd);
        return -1;
    }

    write(fd,&mode,1);
    close(fd);
    return 0;

}

char get_auxin(void)
{
    int fd;
    int ret;
    char buffer[8];

    fd = open("/dev/misc_auxin",O_RDWR);
    if(fd<0){
            printf("****open serial port failed***\n");
            return -1;
     }

     ret = read(fd,buffer,1);
     if(ret < 0)
     {
            printf("get auxin statue failed \n");
            close(fd);
            return -1;
     }

     close(fd);

     if(buffer[0] == 'i' || buffer[0] == 'o')
         return buffer[0];
      else
            return -1;


}


/*
 * Class:     com_dsn_andy_bgmlauncher_auxin_MyJNI
 * Method:    setAuxin
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_com_dsn_andy_bgmlauncher_auxin_MyJNI_setAuxin
  (JNIEnv * env, jclass jobj, jchar  c)
  {
          return  (jint)set_auxin((char)c);
  }

/*
 * Class:     com_dsn_andy_bgmlauncher_auxin_MyJNI
 * Method:    getAuxin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dsn_andy_bgmlauncher_auxin_MyJNI_getAuxin
  (JNIEnv * env, jclass jobj){
           return (jint)get_auxin();
  }

#ifdef __cplusplus
}
#endif
#endif
